"""empty message

Revision ID: 286c68c29457
Revises: crea_config
Create Date: 2019-10-31 03:31:43.030131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '286c68c29457'
down_revision = 'crea_config'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configurations', sa.Column('offset_paginator', sa.Integer(), nullable=True))
    op.drop_column('configurations', 'paginator_page')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configurations', sa.Column('paginator_page', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('configurations', 'offset_paginator')
    # ### end Alembic commands ###
