"""empty message

Revision ID: 5d1ba61d2b9d
Revises: c67a2a25071b
Create Date: 2019-10-31 03:14:18.243387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1ba61d2b9d'
down_revision = 'c67a2a25071b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('paginator_page', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configurations_email'), 'configurations', ['email'], unique=False)
    op.create_index(op.f('ix_configurations_title'), 'configurations', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configurations_title'), table_name='configurations')
    op.drop_index(op.f('ix_configurations_email'), table_name='configurations')
    op.drop_table('configurations')
    # ### end Alembic commands ###
