"""empty message

Revision ID: c67a2a25071b
Revises: 6da0115a7179
Create Date: 2019-10-28 22:30:24.297768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c67a2a25071b'
down_revision = '6da0115a7179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('description', mysql.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
