GENDER_CHOICES = [
    (u'male', u'Masculino'),
    (u'female', u'Femenino'),
    (u'others', u'Otros'),
]

LEVEL_CHOICES = [
    ('1', u'I'),
    (2, u'II'),
    (3, u'III'),
    (4, u'IV'),
    (5, u'V'),
    (6, u'VI'),
    (7, u'VII'),
    (8, u'VIII'),
    (9, u'IX'),
    (10, u'X'),
    (11, u'XI'),
    (12, u'XII'),
]

NEIGHBORHOOD_CHOICES = [
    ('1', 'Barrio Náutico'),
    (2, 'Barrio Obrero'),
    (3, 'Berisso'),
    (4, 'Barrio Solidaridad'),
    (5, 'Barrio Obrero'),
    (6, 'Barrio Bco. Pcia.'),
    (7, 'Barrio J.B. Justo'),
    (8, 'Barrio Obrero'),
    (9, 'El Carmen'),
    (10, 'El Labrador'),
    (11, 'Ensenada'),
    (12, 'La Hermosura'),
    (13, 'La PLata'),
    (14, 'Los Talas'),
    (15, 'Ringuelet'),
    (16, 'Tolosa'),
    (17, 'Villa Alba'),
    (18, 'Villa Arguello'),
    (19, 'Villa B. C'),
    (20, 'Villa Elvira'),
    (21, 'Villa Nueva'),
    (22, 'Villa Paula'),
    (23, 'Villa Progreso'),
    (24, 'Villa San Carlos'),
    (25, 'Villa Zula'),
]
